import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// components 
import InstallBootstrap from "@/components/bootstrap/InstallBootstrap";
import Navigationbar from "@/components/navbar/Navbar";
import StoreProviderWrapper from "@/components/StoreProviderWrapper"; //

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pacific Ocean Portal",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <StoreProviderWrapper>
      <Navigationbar 
    mainContent={children} 
    topContent={null}
  />
      </StoreProviderWrapper>
        {/* bootstrap  */}
        <InstallBootstrap />
      </body>
    </html>
  );
}
